In [45]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/vscode/.local/lib/python3.11/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /home/vscode/.local/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/vscode/.local/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/vscode/.local/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/vscode/.local/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /home/vscode/.local/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [46]:
import pandas as pd

In [47]:
scmDF = pd.read_csv('/workspaces/test-devcontainer-python/day01/supply_chain_data.csv')
scmDF.head(5)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [48]:
scmDF.tail(5)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
98,skincare,SKU98,19.754605,43,913,8525.952560,Female,53,1,27,...,Chennai,28,581,9,5.604691,Pending,2.908122,Rail,Route A,882.198864
99,haircare,SKU99,68.517833,17,627,9185.185829,Unknown,55,8,59,...,Chennai,29,921,2,38.072899,Fail,0.346027,Rail,Route B,210.743009

In [49]:
scmDF.describe

<bound method NDFrame.describe of    Product type    SKU      Price  Availability  Number of products sold  \
0      haircare   SKU0  69.808006            55                      802
1      skincare   SKU1  14.843523            95                      736
2      haircare   SKU2  11.319683            34                        8
3      skincare   SKU3  61.163343            68                       83
4      skincare   SKU4   4.805496            26                      871
..          ...    ...        ...           ...                      ...
95     haircare  SKU95  77.903927            65                      672
96    cosmetics  SKU96  24.423131            29                      324
97     haircare  SKU97   3.526111            56                       62
98     skincare  SKU98  19.754605            43                      913
99     haircare  SKU99  68.517833            17                      627

    Revenue generated Customer demographics  Stock levels  Lead times  \
0         8661.996792            Non-binary            58           7
1         7460.900065                Female            53          30
2         9577.749626               Unknown             1          10
3         7766.836426            Non-binary            23          13
4         2686.505152            Non-binary             5           3
..                ...                   ...           ...         ...
95        7386.363944               Unknown            15          14
96        7698.424766            Non-binary            67           2
97        4370.916580                  Male            46          19
98        8525.952560                Female            53           1
99        9185.185829               Unknown            55           8

    Order quantities  ...  Location Lead time  Production volumes  \
0                 96  ...    Mumbai        29                 215
1                 37  ...    Mumbai        23                 517
2                 88  ...    Mumbai        12                 971
3                 59  ...   Kolkata        24                 937
4                 56  ...     Delhi         5                 414
..               ...  ...       ...       ...                 ...
95                26  ...    Mumbai        18                 450
96                32  ...    Mumbai        28                 648
97                 4  ...    Mumbai        10                 535
98                27  ...   Chennai        28                 581
99                59  ...   Chennai        29                 921

   Manufacturing lead time Manufacturing costs  Inspection results  \
0                       29           46.279879             Pending
1                       30           33.616769             Pending
2                       27           30.688019             Pending
3                       18           35.624741                Fail
4                        3           92.065161                Fail
..                     ...                 ...                 ...
95                      26           58.890686             Pending
96                      28           17.803756             Pending
97                      13           65.765156                Fail
98                       9            5.604691             Pending
99                       2           38.072899                Fail

    Defect rates  Transportation modes   Routes       Costs
0       0.226410                  Road  Route B  187.752075
1       4.854068                  Road  Route B  503.065579
2       4.580593                   Air  Route C  141.920282
3       4.746649                  Rail  Route A  254.776159
4       3.145580                   Air  Route A  923.440632
..           ...                   ...      ...         ...
95      1.210882                   Air  Route A  778.864241
96      3.872048                  Road  Route A  188.742141
97      3.376238                  Road  Route A  540.132423
98      2.908122                  Rail  Route A  882.198864
99      0.346027                  Rail  Route B  210.743009

[100 rows x 24 columns]>

In [53]:
#scmDF.sort_values("Availability").head(10)
scmDF.sort_values("Availability",ascending=True).head(5)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
52,skincare,SKU52,98.031830,1,820,9435.762609,Male,64,11,11,...,Mumbai,10,727,27,9.166849,Pending,2.122472,Air,Route C,602.898499
45,haircare,SKU45,33.784138,1,24,5267.956808,Male,93,7,52,...,Chennai,25,794,25,66.312544,Pass,3.219605,Rail,Route A,495.305697
29,cosmetics,SKU29,63.447559,3,253,8318.903195,Female,45,5,67,...,Kolkata,16,329,7,39.292876,Pass,3.878099,Road,Route B,764.935376
13,skincare,SKU13,16.160393,5,249,4052.738416,Male,80,8,48,...,Bangalore,23,173,10,97.829050,Pending,1.631074,Road,Route B,547.241005
37,skincare,SKU37,23.399845,5,963,2438.339930,Female,25,8,21,...,Kolkata,24,867,15,34.343277,Pending,2.610288,Sea,Route A,183.932968

In [52]:
scmDF.sort_values("Availability",ascending=False).head(10)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
19,skincare,SKU19,51.123870,100,187,2553.495585,Unknown,48,11,94,...,Chennai,20,694,16,82.373321,Fail,3.646451,Road,Route C,477.307631
84,haircare,SKU84,89.104367,99,618,2048.290100,Unknown,73,26,80,...,Chennai,24,589,22,33.808637,Pass,4.843457,Air,Route B,465.457006
42,skincare,SKU42,46.529168,98,155,1839.609426,Female,22,27,57,...,Bangalore,26,179,7,96.422821,Fail,4.939255,Road,Route A,635.657121
40,skincare,SKU40,80.541424,97,933,5724.959350,Female,90,20,39,...,Kolkata,18,793,1,88.179407,Pending,4.213269,Road,Route A,529.808724
94,cosmetics,SKU94,3.037689,97,987,7888.356547,Unknown,77,26,72,...,Delhi,12,908,14,60.387379,Pass,1.463607,Rail,Route B,846.665257
34,skincare,SKU34,37.467592,96,602,9061.710896,Unknown,1,26,21,...,Chennai,4,452,10,10.754273,Pass,0.646605,Road,Route B,510.358000
11,skincare,SKU11,90.635460,95,960,6099.944116,Female,46,23,60,...,Kolkata,28,362,11,27.592363,Pending,0.021170,Air,Route A,126.723033
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
15,skincare,SKU15,36.989245,94,469,5442.086785,Non-binary,9,8,69,...,Bangalore,14,580,7,97.121282,Pass,2.264406,Sea,Route B,127.861800
53,skincare,SKU53,30.341471,93,242,8232.334829,Male,96,25,54,...,Delhi,1,631,17,83.344059,Pending,1.410348,Air,Route B,750.737841

In [55]:
scmDF ["Product type"].value_counts()

Product type
skincare     40
haircare     34
cosmetics    26
Name: count, dtype: int64

In [56]:
scmDF [scmDF ["Availability"]>50]

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
5,haircare,SKU5,1.699976,87,147,2828.348746,Non-binary,90,27,66,...,Bangalore,10,104,17,56.766476,Fail,2.779194,Road,Route A,235.461237
7,cosmetics,SKU7,42.958384,59,426,8496.103813,Female,93,17,11,...,Bangalore,22,564,1,99.466109,Fail,0.398177,Road,Route C,802.056312
8,cosmetics,SKU8,68.717597,78,150,7517.363211,Female,5,10,15,...,Mumbai,13,769,8,11.423027,Pending,2.709863,Sea,Route B,505.557134
11,skincare,SKU11,90.635460,95,960,6099.944116,Female,46,23,60,...,Kolkata,28,362,11,27.592363,Pending,0.021170,Air,Route A,126.723033
15,skincare,SKU15,36.989245,94,469,5442.086785,Non-binary,9,8,69,...,Bangalore,14,580,7,97.121282,Pass,2.264406,Sea,Route B,127.861800
16,skincare,SKU16,7.547172,74,280,6453.797968,Female,2,5,78,...,Bangalore,3,399,21,77.106342,Pass,1.012563,Air,Route A,865.525780
17,cosmetics,SKU17,81.462534,82,126,2629.396435,Female,45,17,85,...,Chennai,7,453,16,47.679680,Fail,0.102021,Air,Route C,670.934391
19,skincare,SKU19,51.123870,100,187,2553.495585,Unknown,48,11,94,...,Chennai,20,694,16,82.373321,Fail,3.646451,Road,Route C,477.307631
21,cosmetics,SKU21,84.893869,60,601,7087.052696,Unknown,69,25,7,...,Chennai,19,791,4,61.735729,Pending,0.018608,Air,Route C,523.360915
22,haircare,SKU22,27.679781,55,884,2390.807867,Unknown,71,1,63,...,Kolkata,22,780,28,50.120840,Fail,2.591275,Rail,Route C,205.571996
25,haircare,SKU25,39.629344,73,142,2174.777054,Male,82,11,52,...,Kolkata,19,934,23,78.280383,Pending,3.797231,Road,Route B,458.535946
33,cosmetics,SKU33,64.795435,63,616,5149.998350,Non-binary,4,17,95,...,Chennai,1,251,23,23.853428,Fail,3.541046,Sea,Route A,371.255296
34,skincare,SKU34,37.467592,96,602,9061.710896,Unknown,1,26,21,...,Chennai,4,452,10,10.754273,Pass,0.646605,Road,Route B,510.358000
38,cosmetics,SKU38,52.075931,75,705,9692.318040,Non-binary,69,1,88,...,Mumbai,10,841,12,5.930694,Pending,0.613327,Air,Route B,339.672870
40,skincare,SKU40,80.541424,97,933,5724.959350,Female,90,20,39,...,Kolkata,18,793,1,88.179407,Pending,4.213269,Road,Route A,529.808724
42,skincare,SKU42,46.529168,98,155,1839.609426,Female,22,27,57,...,Bangalore,26,179,7,96.422821,Fail,4.939255,Road,Route A,635.657121
46,haircare,SKU46,27.082207,75,859,2556.767361,Non-binary,92,29,6,...,Chennai,18,870,23,77.322353,Pending,3.648611,Road,Route B,380.435937
47,skincare,SKU47,95.712136,93,910,7089.474250,Male,4,15,51,...,Kolkata,10,964,20,19.712993,Pending,0.380574,Rail,Route A,581.602355
50,cosmetics,SKU50,14.203484,91,633,5910.885390,Female,31,23,82,...,Delhi,20,306,21,45.178758,Fail,4.754801,Rail,Route B,496.248650
51,haircare,SKU51,26.700761,61,154,9866.465458,Male,100,4,52,...,Bangalore,18,673,28,14.190328,Pending,1.772951,Road,Route A,694.982318
53,skincare,SKU53,30.341471,93,242,8232.334829,Male,96,25,54,...,Delhi,1,631,17,83.344059,Pending,1.410348,Air,Route B,750.737841
56,skincare,SKU56,20.986386,90,93,4767.020484,Non-binary,25,23,83,...,Mumbai,24,826,28,12.836285,Pass,1.173755,Air,Route B,832.210809
57,haircare,SKU57,49.263205,65,227,1605.866900,Unknown,5,18,51,...,Delhi,21,588,25,67.779623,Pending,2.511175,Rail,Route A,482.191239
58,skincare,SKU58,59.841561,81,896,2021.149810,Non-binary,10,5,44,...,Delhi,18,396,7,65.047415,Fail,1.730375,Road,Route B,110.364335
62,cosmetics,SKU62,72.796354,89,270,3899.746834,Unknown,86,2,40,...,Mumbai,13,751,14,21.048643,Pass,1.874001,Sea,Route C,320.846516
63,skincare,SKU63,13.017377,55,246,4256.949141,Non-binary,54,19,10,...,Bangalore,18,736,10,20.075004,Pending,3.632843,Sea,Route A,687.286178
65,skincare,SKU65,33.697717,72,457,8354.579686,Male,57,24,54,...,Kolkata,16,358,21,1.597223,Fail,4.911096,Rail,Route C,555.859104
66,skincare,SKU66,26.034870,52,704,8367.721618,Female,13,17,19,...,Kolkata,24,867,28,42.084437,Fail,3.448063,Road,Route A,393.843349
69,skincare,SKU69,54.865529,62,511,1752.381087,Non-binary,95,1,27,...,Kolkata,9,862,7,77.627766,Pending,1.362388,Air,Route A,207.663206
70,haircare,SKU70,47.914542,90,32,7014.887987,Female,10,12,22,...,Bangalore,22,775,16,11.440782,Pass,1.830576,Road,Route C,183.272899
72,cosmetics,SKU72,90.204428,88,478,2633.121981,Non-binary,57,29,77,...,Bangalore,21,152,11,55.760493,Pending,3.213330,Rail,Route B,677.944570
74,haircare,SKU74,3.170011,64,904,5709.945296,Female,41,6,1,...,Delhi,1,919,9,80.580852,Fail,0.396613,Rail,Route A,341.552657
79,haircare,SKU79,57.057031,56,198,7888.723268,Non-binary,31,25,20,...,Bangalore,5,228,12,57.870903,Pending,0.165872,Air,Route C,351.504219
80,skincare,SKU80,91.128318,75,872,8651.672683,Unknown,39,14,41,...,Chennai,8,202,5,76.961228,Fail,2.849662,Sea,Route B,787.779850
83,haircare,SKU83,68.911246,82,663,2411.754632,Unknown,65,24,7,...,Bangalore,20,443,5,97.730594,Fail,0.773006,Road,Route A,682.971018
84,haircare,SKU84,89.104367,99,618,2048.290100,Unknown,73,26,80,...,Chennai,24,589,22,33.808637,Pass,4.843457,Air,Route B,465.457006
85,cosmetics,SKU85,76.962994,83,25,8684.613059,Female,15,18,66,...,Chennai,4,211,2,69.929346,Fail,1.374429,Road,Route B,842.686830
88,cosmetics,SKU88,75.270407,58,737,9444.742033,Male,60,18,85,...,Mumbai,21,953,11,68.184919,Pending,0.722204,Sea,Route A,103.916248
90,skincare,SKU90,13.881914,56,320,9592.633570,Non-binary,66,18,96,...,Bangalore,8,585,8,85.675963,Pass,1.219382,Rail,Route B,990.078473
91,cosmetics,SKU91,62.111965,90,916,1935.206794,Male,98,22,85,...,Delhi,5,207,28,39.772883,Pending,0.626002,Rail,Route B,996.778315
93,haircare,SKU93,69.290831,88,114,4531.402134,Unknown,63,17,66,...,Chennai,21,824,20,35.633652,Fail,4.165782,Air,Route A,823.523846
94,cosmetics,SKU94,3.037689,97,987,7888.356547,Unknown,77,26,72,...,Delhi,12,908,14,60.387379,Pass,1.463607,Rail,Route B,846.665257
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423

In [61]:
# scmDF[(scmDF["Availability"] > 50) & (scmDF["Availability"] > 50)]

scmDF[ (scmDF["Availability"] >50) & (scmDF["Availability"]<=60) ].sort_values("Availability")

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
66,skincare,SKU66,26.034870,52,704,8367.721618,Female,13,17,19,...,Kolkata,24,867,28,42.084437,Fail,3.448063,Road,Route A,393.843349
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
63,skincare,SKU63,13.017377,55,246,4256.949141,Non-binary,54,19,10,...,Bangalore,18,736,10,20.075004,Pending,3.632843,Sea,Route A,687.286178
22,haircare,SKU22,27.679781,55,884,2390.807867,Unknown,71,1,63,...,Kolkata,22,780,28,50.120840,Fail,2.591275,Rail,Route C,205.571996
79,haircare,SKU79,57.057031,56,198,7888.723268,Non-binary,31,25,20,...,Bangalore,5,228,12,57.870903,Pending,0.165872,Air,Route C,351.504219
90,skincare,SKU90,13.881914,56,320,9592.633570,Non-binary,66,18,96,...,Bangalore,8,585,8,85.675963,Pass,1.219382,Rail,Route B,990.078473
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
88,cosmetics,SKU88,75.270407,58,737,9444.742033,Male,60,18,85,...,Mumbai,21,953,11,68.184919,Pending,0.722204,Sea,Route A,103.916248
7,cosmetics,SKU7,42.958384,59,426,8496.103813,Female,93,17,11,...,Bangalore,22,564,1,99.466109,Fail,0.398177,Road,Route C,802.056312
21,cosmetics,SKU21,84.893869,60,601,7087.052696,Unknown,69,25,7,...,Chennai,19,791,4,61.735729,Pending,0.018608,Air,Route C,523.360915

In [ ]:
scmDF.rename(columns={'Number of products sold': 'Sold count'}, inplace=True)
scmDF.describe()

In [62]:
scmDF[scmDF["Number of products sold"].isna()]

Empty DataFrame
Columns: [Product type, SKU, Price, Availability, Number of products sold, Revenue generated, Customer demographics, Stock levels, Lead times, Order quantities, Shipping times, Shipping carriers, Shipping costs, Supplier name, Location, Lead time, Production volumes, Manufacturing lead time, Manufacturing costs, Inspection results, Defect rates, Transportation modes, Routes, Costs]
Index: []

[0 rows x 24 columns]

In [65]:
group_by_producttype = scmDF.groupby("Product type")

group_by_producttype.first()

,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,Shipping times,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
Product type,,,,,,,,,,,,,,,,,,,,,
cosmetics,SKU7,42.958384,59,426,8496.103813,Female,93,17,11,1,...,Bangalore,22,564,1,99.466109,Fail,0.398177,Road,Route C,802.056312
haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,4,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,2,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579

In [66]:
scm_pivot_table = scmDF.pivot_table(index="Product type", columns="SKU", values="Availability")
scm_pivot_table.describe()

SKU,SKU0,SKU1,SKU10,SKU11,SKU12,SKU13,SKU14,SKU15,SKU16,SKU17,...,SKU90,SKU91,SKU92,SKU93,SKU94,SKU95,SKU96,SKU97,SKU98,SKU99
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,55.0,95.0,11.0,95.0,41.0,5.0,26.0,94.0,74.0,82.0,...,56.0,90.0,44.0,88.0,97.0,65.0,29.0,56.0,43.0,17.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,55.0,95.0,11.0,95.0,41.0,5.0,26.0,94.0,74.0,82.0,...,56.0,90.0,44.0,88.0,97.0,65.0,29.0,56.0,43.0,17.0
25%,55.0,95.0,11.0,95.0,41.0,5.0,26.0,94.0,74.0,82.0,...,56.0,90.0,44.0,88.0,97.0,65.0,29.0,56.0,43.0,17.0
50%,55.0,95.0,11.0,95.0,41.0,5.0,26.0,94.0,74.0,82.0,...,56.0,90.0,44.0,88.0,97.0,65.0,29.0,56.0,43.0,17.0
75%,55.0,95.0,11.0,95.0,41.0,5.0,26.0,94.0,74.0,82.0,...,56.0,90.0,44.0,88.0,97.0,65.0,29.0,56.0,43.0,17.0
max,55.0,95.0,11.0,95.0,41.0,5.0,26.0,94.0,74.0,82.0,...,56.0,90.0,44.0,88.0,97.0,65.0,29.0,56.0,43.0,17.0

In [ ]:
pip install openpyxl

In [ ]:
scmDF.to_excel('output_scmproducts.xlsx', sheet_name='Sheet1', index=False)